android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
kotlin.code.style=official
android.nonTransitiveRClass=true
# Compose compiler metrics (useful for debugging recompositions)
# kotlin.compose.compilerMetricsDestination=build/compose-metrics

# Increase Gradle Heap Size to fix OutOfMemoryError during dex merging
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
